<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20190116171322 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return 'Add required database structures for ShortUrl storage.';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE obisconcept_shorturls_domain_model_shorturl (persistence_object_identifier VARCHAR(40) NOT NULL, creator VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, link VARCHAR(255) NOT NULL, target VARCHAR(255) NOT NULL, creationdate DATETIME NOT NULL, validfrom DATETIME DEFAULT NULL, validuntil DATETIME DEFAULT NULL, INDEX IDX_41FB90F9BC06EA63 (creator), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE obisconcept_shorturls_domain_model_shorturl ADD CONSTRAINT FK_41FB90F9BC06EA63 FOREIGN KEY (creator) REFERENCES neos_neos_domain_model_user (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('DROP TABLE obisconcept_shorturls_domain_model_shorturl');
    }
}
