-
  name: 'Linking Service'
  uriPattern: '{identifier}'
  defaults:
    '@package': 'ObisConcept.ShortUrls'
    '@controller': 'ShortUrl'
    '@action': 'redirectToTarget'
  toLowerCase: false
  routeParts:
    'identifier':
      handler: 'ObisConcept\ShortUrls\Routing\RoutePartHandler\ValidShortUrl'
