-
  name: 'Linking Service'
  uriPattern: '{id}'
  defaults:
    '@package': 'ObisConcept.ShortUrls'
    '@controller': 'ShortUrl'
    '@action': 'redirectToTarget'
    '@format': 'html'
  routeParts:
    'id':
      toLowerCase: false
      handler: 'ObisConcept\ShortUrls\Routing\RoutePartHandler\ValidShortUrl'
