Neos:
  Neos:
    modules:
      'management':
        submodules:
          'shortUrls':
            label: 'Short URLs'
            controller: 'ObisConcept\ShortUrls\Controller\StandardController'
            description: 'Create short urls for your content to ease the sharing of pagelinks.'
            icon: 'icon-link'